### ISSUE TITLE
Double-tapping doesn't work like double-clicking

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#1]
To select a gate, you can double-click anywhere on the "tile", but double-tapping doesn't work the same way. Only the output circle seems to be sensitive to double-tapping. Tested on both iPad (Safari) and laptop (Chrome).

**Comment by dakotacookenmaster** [comment]
Hm, I'll need to do some testing on this. If I can leave it with the `DoubleClick` event, I will, otherwise I may have to use something like `TouchEvent`.

![image](https://github.com/dakotacookenmaster/cptr-108-digital-logic-simulator-lab/assets/48303855/822a7b1e-0dbd-4b17-8241-70f0e297651a)
