### ISSUE TITLE
Only show ConnectModal when there's more than 1 input (available?)

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#12]
Th ability to select which pin to connect to is **great**! For gates with only 1 input (NOT, OUTPUT), however, it's a superfluous step. Would it be possible to skip the selection step if the receiving gate only has 1 input?

I think the receiving pin selection step could also be skipped if there's only 1 input pin that's not currently connected on the receiving gate, but I'm not as certain about that. Might be worth considering, though.

**Comment by dakotacookenmaster** [comment]
Good catch. I thought about this but simply didn't get to it yet.

**Comment by dakotacookenmaster** [comment]
Fixed in version `1.4.0`
