### ISSUE TITLE
Minor wording tweaks

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#15]
These are fairly small details. Spit & polish. ;-)
1. "Logical Gates" above the left pane should be "Logic Gates". Actually, they're not all gates, so perhaps "Components" would be better.
2. "Provided Resources" at the bottom of each description are obviously provided, so just say "Resources"
3. "7 Seg Display" should use a single 7-segment display in the icon, and if it were labeled "7-Seg Disp", the whole column of components could take up less space.

**Comment by dakotacookenmaster** [comment]
@ProfessorO  Good suggestions! I'll talk about them:

1 & 2 - I completely agree. I will make these changes in the next version release. 

3 - I would use a single 7-segment display in the icon, but the icon library I'm using doesn't currently have one that matches the app's color palette. For now, this is a `wontfix`, but if you happen to find a free icon that you think would readily match, I'm happy to adopt it.
