### ISSUE TITLE
Display current results next to (or as different from) target truth table

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#16]
The truth table generated from the assignment is wonderful. A cool enhancement would be to add another set of output columns showing what the circuit is currently generating (actual vs expected). Or perhaps highlighting which cells in each output column aren't currently being matched.

**Comment by dakotacookenmaster** [comment]
This is a great idea!

**Comment by dakotacookenmaster** [comment]
Fixed in `1.4.1`
