### ISSUE TITLE
Color the whole input & output "gate" instead of just the connection point

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#3]
Making the whole input or output gate show its state would make it far more obvious. I think this is more important for outputs than inputs, but might be as simple as changing the background of the main tile.

**Comment by dakotacookenmaster** [comment]
This is fairly similar to #7 . I'll see if I can't kill two birds with one stone.

**Comment by dakotacookenmaster** [comment]
I tried to do this well, and it really just looked gross with the icons😆 . Right now, I'm going to mark as `wontfix`, but if anyone finds a reasonable way to make this look, I'm happy to re-open the issue or review any PRs.
