### ISSUE TITLE
Generate truth table visualization from assignment

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#5]
Since the expected truth table is already in the assignment file, it would be nice to generate the truth table students see from that. In theory, it should "just" be a simple HTML table with a little styling. Once that's done, it would be nice to add a setting in the assignment file to determine whether to display the auto-generated truth table  for each challenge or not.

**Comment by dakotacookenmaster** [comment]
This should actually be super easy, and could be accessed via a modal, much like a lot of the other actions. Please consider contributing to the code base and adding this!

**Comment by dakotacookenmaster** [comment]
Feature added in `1.3.2`
