### ISSUE TITLE
Make connecting & toggling default click actions

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#6]
I like the context menu (though I haven't gotten a chance to try it on my iPad yet). I'd prefer to have "connect" or "disconnect" be the default when I click on a gate's input/output bubbles (depending on the current connection state, and perhaps a confirmation for disconnection, since it's destructive), and "toggle" be the default when I click on the input itself.

**Comment by dakotacookenmaster** [comment]
The "click" action is already highly utilized on most elements, and adding additional layers to that might prove to be challenging. I probably won't label this as `wontfix` for now, but it's probably the lowest priority of the issues.

**Comment by dakotacookenmaster** [comment]
Decided that this is a `wontfix` issue.
