### ISSUE TITLE
Use a toggle icon for input "gate"

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/cptr-108-digital-logic-simulator-lab#7]
Since we're not getting input from anywhere else (i.e., no nested circuits), it might make sense to use an actual switch as the visual representation of an input. Perhaps one of these:

https://icons8.com/icons/set/switch--animated

**Comment by dakotacookenmaster** [comment]
Hm, I'm curious how you visualize this. Simply change the inputs to an animated icon, but keep the "output" pin of the input intact? 

We could technically remove the output pin altogether for the input and have it like to the toggle itself...that's entirely visual. Let me know your thoughts.

**Comment by ProfessorO** [comment]
This idea is a bit risky--we might end up confusing input components with switches (toggle or otherwise). Let me think about it a bit more.

**Comment by dakotacookenmaster** [comment]
@ProfessorO I went ahead and added a toggle in addition to the context menu. Easy to add, easy to remove. Let me know what you think about this feature. For now, I'm closing this issue.
